Parameters:
  BucketName: 
    Description: What to name the bucket
    Type: String
  DomainName:
    Description: Domain to add as alias to Cloudfront Distribution
    Type: String
  CertificateArn:
    Description: ARN of certificate to attach to cloudfront
    Type: String

Resources:
  WebAppS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  WebAppS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebAppS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
            - s3:GetObject
            Resource: !Sub arn:aws:s3:::${BucketName}/*
  WebAppCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${BucketName}.s3-website-${AWS::Region}.amazonaws.com
            Id: WebApp
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: 'true'
        Aliases:
        - !Ref DomainName
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: WebApp
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

Outputs:
  CloudfrontDomain:
    Value: !GetAtt WebAppCloudFrontDistribution.DomainName