AWSTemplateFormatVersion: 2010-09-09
Description: Creates an AWS WAF and attaches it to the ELB

Parameters:
  ElbArn:
    Description: 'ARN for the ELB to attach WAF to'
    Type: String
  NamePrefix:
    Description: Provide string to be the prefixed to the name of created resources
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: can contain only ASCII characters

Resources:
  WafAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref ElbArn
      WebACLArn: !GetAtt WafAcl.Arn

  WafAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Description: WebACL for the WAF
      Name: !Sub ${NamePrefix}-waf
      Rules:
        - Name: RuleWithAWSManagedRules
          Priority: 0
          OverrideAction:
            Count: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithAWSManagedRulesMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: []
        - Name: BlockXssAttack
          Priority: 1
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockXssAttackMetric
          Statement:
            XssMatchStatement:
              FieldToMatch:
                AllQueryArguments: {}
              TextTransformations:
                - Priority: 1
                  Type: NONE
      Scope: REGIONAL
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${NamePrefix}-waf
